USER_NAME = kajih
CONVERT_TO = liatris

SPLIT_KEYBOARD = yes
SPLIT_TRANSPORT_MIRROR = yes
SPLIT_LAYER_STATE_ENABLE = yes
SPLIT_MODS_ENABLE = yes
SPLIT_ACTIVITY_ENABLE = yes

OLED_ENABLE = yes
QUANTUM_PAINTER_ENABLE = no # GPT

ENCODER_ENABLE = yes
KEY_OVERRIDE_ENABLE = no # Kyriel

BOOTMAGIC_ENABLE = yes
LAYER_LOCK_ENABLE = yes
CAPS_WORD_ENABLE = yes

TAP_DANCE_ENABLE = yes
MOUSEKEY_ENABLE = yes
CONSOLE_ENABLE = yes      # for debugging ?

RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_CUSTOM_USER = no # kyrial
RGB_MATRIX_LAYER_INDICATORS = yes

WS2812_DRIVER = vendor
RGB_MATRIX_DRIVER = ws2812

