OLED_ENABLE = yes
ENCODER_ENABLE = yes

KEY_OVERRIDE_ENABLE = no # Kyriel

CONVERT_TO=liatris
SPLIT_KEYBOARD = yes
CAPS_WORD_ENABLE = yes
LAYER_LOCK_ENABLE = yes

TAP_DANCE_ENABLE = yes
CONSOLE_ENABLE = yes      # for debugging ?
MOUSEKEY_ENABLE = yes

RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
RGBLIGHT_ANIMATIONS = yes

WS2812_DRIVER = vendor
RGB_MATRIX_DRIVER = ws2812

RGB_MATRIX_CUSTOM_USER = no
